// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZooAPI.Data;

#nullable disable

namespace ZooAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240303214333_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZooCore.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<int>("FamilyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal?>("Size")
                        .HasPrecision(37, 2)
                        .HasColumnType("numeric(37,2)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(37, 2)
                        .HasColumnType("numeric(37,2)");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 12,
                            Color = "Dark grey",
                            FamilyId = 1,
                            Name = "Balou",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 10,
                            Color = "Orange",
                            FamilyId = 2,
                            Name = "Tigrou",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 3,
                            Age = 37,
                            Color = "Brown body with white head",
                            FamilyId = 3,
                            Name = "USA",
                            SpeciesId = 5
                        });
                });

            modelBuilder.Entity("ZooCore.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Family");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ursidae"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Felin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Avian"
                        });
                });

            modelBuilder.Entity("ZooCore.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FamilyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FamilyId = 2,
                            Name = "Tiger"
                        },
                        new
                        {
                            Id = 2,
                            FamilyId = 2,
                            Name = "Lion"
                        },
                        new
                        {
                            Id = 3,
                            FamilyId = 1,
                            Name = "BlackBear"
                        },
                        new
                        {
                            Id = 4,
                            FamilyId = 1,
                            Name = "PolarBear"
                        },
                        new
                        {
                            Id = 5,
                            FamilyId = 3,
                            Name = "Eagle"
                        });
                });

            modelBuilder.Entity("ZooCore.Animal", b =>
                {
                    b.HasOne("ZooCore.Family", "Family")
                        .WithMany("Animals")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooCore.Species", "Species")
                        .WithMany("Animals")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("ZooCore.Species", b =>
                {
                    b.HasOne("ZooCore.Family", "Family")
                        .WithMany("Species")
                        .HasForeignKey("FamilyId");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("ZooCore.Family", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("ZooCore.Species", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
