// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZooAPI.Data;

#nullable disable

namespace ZooAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ZooCore.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Family")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Size")
                        .HasPrecision(37, 2)
                        .HasColumnType("decimal(37,2)");

                    b.Property<int>("Species")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(37, 2)
                        .HasColumnType("decimal(37,2)");

                    b.HasKey("Id");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 12,
                            Color = "Dark grey",
                            Family = 2,
                            Name = "Balou",
                            Species = 2
                        },
                        new
                        {
                            Id = 2,
                            Age = 10,
                            Color = "Orange",
                            Family = 0,
                            Name = "Tigrou",
                            Species = 0
                        },
                        new
                        {
                            Id = 3,
                            Age = 37,
                            Color = "Brown",
                            Family = 1,
                            Name = "USA",
                            Species = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
